#!/usr/bin/env node
const userName = process.env.BROWSERSTACK_USER
const accessKey = process.env.BROWSERSTACK_ACCESS_KEY

if (!userName) {
  throw new Error('process.env.BROWSERSTACK_USER is required to run browserstack e2e tests')
}

if (!accessKey) {
  throw new Error('process.env.BROWSERSTACK_ACCESS_KEY is required to run browserstack e2e tests')
}

const browserstackURL = `https://${userName}:${accessKey}@hub-cloud.browserstack.com/wd/hub`

const selenium = require('./selenium-system.js')
;(async () => {
  const 
  // Input capabilities
  const capabilities = {
    name: '@consento/sync-randombytes',
    build: process.env.GITHUB_RUN_ID || 'dirty',
    os: process.env.BROWSERSTACK_OS || 'Windows',
    os_version: process.env.BROWSERSTACK_OS_VERSION || '7',
    browserName: process.env.BROWSERSTACK_BROWSER_NAME || 'Internet Explorer',
    browser_version: process.env.BROWSERSTACK_BROWSER_VERSION || '10',
    'browserstack.console': 'verbose',
    'browserstack.video': false,
    'browserstack.debug': true
  }

  await selenium(
    builder => builder
      .usingServer(browserstackURL)
      .withCapabilities(capabilities)
  )
}).then(
  failed => {
    process.exit(failed ? 1 : 0)
  },
  err => {
    console.error(err)
    process.exit(2)
  }
)
