#!/usr/bin/env node

const crypto = require('crypto')
const path = require('path')
const randomName = crypto.randomFillSync
  ? (/^v8\./.test(process.version)
    ? 'getRandomValuesNodeEq8'
    : 'getRandomValuesNodeGt8'
  )
  : 'getRandomValuesNodeLt8'

require(path.resolve(process.cwd(), process.argv[2]))(randomName)
