#!/usr/bin/env node

const crypto = require('crypto')
const path = require('path')
const randomName = crypto.randomFillSync
  ? (
    /^v(\d+)/.exec(process.version)[1] < 9 ? 'getRandomValuesRandomFillUint8'
    : 'getRandomValuesRandomFill'
  )
  : 'getRandomValuesRandomBytes'

require(path.resolve(process.cwd(), process.argv[2]))(randomName)
